a = {}
a = {0}
a = {0,}
a = {0, 1}
a = {0, 1,}
a = {"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
a = {"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
a = {"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", {"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"}, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
a = {"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", {"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"}, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
